### ISSUE TITLE
index out of range on twentemilieu.py get_data

### ISSUE THREAD

**Issue by dtx3k** [heyajohnny/afvalinfo#100]
issue on fresh config / install of afvalinfo

config in HA:
postcode and streetnumber are "sensored"

```yaml

sensor:
    - platform: afvalinfo
      resources:
        - pbd
        - gft
        - trash_type_today
        - trash_type_tomorrow
      location: hengelo
      postcode: 75xxaa
      streetnumber: 1337
      locale: 'nl'
      timespanindays: 365
```

error occurs for each resource item in configuration
Error log:

`
2020-06-07 22:31:10 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.afvalinfo_gft fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 472, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/afvalinfo/sensor.py", line 507, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/afvalinfo/sensor.py", line 430, in update
    self.location, self.postcode, self.street_number, self.resources
  File "/config/custom_components/afvalinfo/location/twentemilieu.py", line 40, in get_data
    uniqueId = r.json()["dataList"][0]["UniqueId"]
IndexError: list index out of range`
