### ISSUE TITLE
Use “days until” instead of date?

### ISSUE THREAD

**Issue by MvZeeland** [heyajohnny/afvalinfo#107]
Is it possible to show the “days until” instead of the date?

**Comment by heyajohnny** [comment]
You can use a template in your 'configuration.yaml' to get the attribute 'days_until_collection_date'. Look at this example:
```
  - platform: template
    sensors:
      paper_days_until_collection:
        value_template: "{{ state_attr('sensor.afvalinfo_papier', 'days_until_collection_date') }}"
```
