### ISSUE TITLE
unable to validate configuration after adding afvalinfo

### ISSUE THREAD

**Issue by GitHubxtsnl** [heyajohnny/afvalinfo#111]
running:
Home Assistant 0.111.4
HassOS 4.10
HACS 1.1.1
afvalinfo v0.5.14-2

When I add the following to my configuration.yaml and do a **Configuration Validation** via Server Controls the color wheel just keeps spinning forever. As soon as I comment out all the lines below (except sensor:) the **Configuration Validation** finishes in ~5 seconds.

```
sensor:
  - platform: afvalinfo
    resources:
      - pbd
      - gft
      - papier
    location: !secret general_address_location (using 'arnhem' as location in secrets.yaml file)
    postcode: !secret general_address_zipcode (using 'xxxyy' as postcode in secrets.yaml file)
    streetnumber: !secret general_address_number (using '39' as streetnumber in secrets.yaml file)
```
