### ISSUE TITLE
No data anymore

### ISSUE THREAD

**Issue by Roelofk85** [heyajohnny/afvalinfo#115]
Hello,

I don't get the data anymore.
Changed nothing, all the sensors say "onbekend".

Config:
```
  - platform: afvalinfo
    resources:
      - restafval
      - papier
      - gft
      - trash_type_today
      - trash_type_tomorrow
    location: terschelling
    postcode: mycode
    streetnumber: 1
    locale: 'nl'
    timespanindays: 14
```

Am i doing something wrong?

Thanks!

Roelof
