### ISSUE TITLE
Suggestion to include a identifier to allow for multiple afvalinfo entities

### ISSUE THREAD

**Issue by Bram1nat0r** [heyajohnny/afvalinfo#125]
Hi,

Big fan and user of the afvalinfo integration!
Sometimes I would like to know when collection day is , in the adjacent part of my neighborhood so I can dump some stuff there :-)
I am able to configure multiple instances of the afvalinfo sensor, but right now they show up as :

sensor.afvalinfo_papier
sensor.afvalinfo_papier_2
sensor.afvalinfo_papier_3

It would be nice to add a 'identifier' option, like so :

```
- platform: afvalinfo
  sensors:
    custom_id_1:
      resources:
        - papier
      location: eindhoven
      postcode: 1234RS
      streetnumber: 16
      dateformat: '%A %d %B'
      locale: 'nl'
      timespanindays: 14

    custom_id_2:
      resources:
        - papier
      location: eindhoven
      postcode: 2345BE
      streetnumber: 12
      dateformat: '%A %d %B'
      locale: 'nl'
      timespanindays: 14

    custom_id_3:
      resources:
        - papier
      location: eindhoven
      postcode: 2345BE
      streetnumber: 12
      dateformat: '%A %d %B'
      locale: 'nl'
      timespanindays: 14
```

Which results in entities :

sensor.afvalinfo_custom_id_1_papier
sensor.afvalinfo_custom_id_2_papier
sensor.afvalinfo_custom_id_3_papier
