### ISSUE TITLE
Unknown State Sudwest Fryslan 

### ISSUE THREAD

**Issue by johanb7** [heyajohnny/afvalinfo#139]
The afvalinfo for Sudwest Fryslan (zuidwest friesland) doesn't seem to work anymore.
I get the status Unknown on the GFT and Restafval and status None at Afval Today

**Comment by RvNoort** [comment]
I've installed this extension today and had the exact same isue. If you followed the attribute example, sensor.afvalinfo_gft is used but it looks like the naming is changed. It will now be sensor.afvalinfo_'your id in config'_gft. I've found this in Developer Tools -> states.

I hope this will solve it for you.

**Comment by johanb7** [comment]
I didn't have an ID in my config, just added it but same result

**Comment by heyajohnny** [comment]
Please specify a postcode / streetnumber that doesn't work as expected. It works fine with these settings:
```
- platform: afvalinfo
    resources:
      - gft
      - pbd
      - papier
      - restafval
      - textiel
      - trash_type_today
      - trash_type_tomorrow
    location: Zuidwest-Friesland
    postcode: 8605bt
    streetnumber: 31
    dateformat: "%d-%m-%Y"
    locale: "nl"
    timespanindays: 365
```
