### ISSUE TITLE
Lippenhuizen / Smallingerland niet ondersteund?

### ISSUE THREAD

**Issue by Senaxx** [heyajohnny/afvalinfo#144]
Logger: custom_components.afvalinfo.const.const
Source: custom_components/afvalinfo/location/mijnafvalwijzer.py:94
Integration: afvalinfo (documentation)
First occurred: 4:14:17 (1 occurrences)
Last logged: 4:14:17

Error occurred while fetching data: 'Not Found'

```
sensor:
  - platform: afvalinfo
    id: bukenhage
    resources:                       
      - gft
      - papier
      - restafval
      - trash_type_today
      - trash_type_tomorrow
    location: Smallingerland
    postcode: 8408HS                 
    streetnumber: 13                 
    dateformat: '%d-%m-%Y'           
    locale: 'nl'
    timespanindays: 365
```

Op mijnafvalwijzer levert de URL: https://www.mijnafvalwijzer.nl/nl/8408HS/13/ ook niets op.
Voor nu moet ik de informatie halen van: https://www.omrin.nl/bij-mij-thuis/afval-regelen/afvalkalender.
