### ISSUE TITLE
aanpassen entity-picture naar state

### ISSUE THREAD

**Issue by meijeringeu** [heyajohnny/afvalinfo#180]
Top app, mooi dat hij de meeste gemeentes werkt. Ik kan namelijk de afvalwijzer niet gebruiken omdat onze gemeente niet wordt ondersteund.

Ik zoek een mogelijkheid om een entity-picture te tonen nav de status. Nu heb ik dit geregeld en alle sensoren gebruiken nu de afbeelding van het afval, us 1 entity-picture voor een sensor lukt prima. 

Echter de "sensor.afvalinfo_next_trash_type_and_date" wil ik graag aanpassen op de eerst volgende leging (dus bij restafval een local/icon/restafval.png, bij GFT: local/icon/gft.png en bij textiel: textiel.png).
Het lukt me niet om customize.yaml zo aan te passen dat dit kan werken. 
Ik wil het graag in de customize.yaml doen, omdat ik een badge aan mijn dashboard wil hangen, zodat ik snel zie welke container geleegd met worden.

Hebben jullie mogelijk een idee hiervoor?

**Comment by heyajohnny** [comment]
Ik denk niet dat het mogelijk is wat je wilt. Ik zie zo snel alleen deze [oplossing](https://community.home-assistant.io/t/customizing-entities-changing-friendly-names/189411/3)

**Comment by floriskruisselbrink** [comment]
Ik heb zelf twee nieuwe template-sensors gemaakt die eigenlijk de bestaande sensor.afvalinfo_today en sensor.afvalinfo_tomorrow nabootsen, maar dan met een entity-picture die past bij het aangegeven type afval. Deze wordt opgehaald uit de configuratie van de betreffende sensor (hij neemt b.v. de entity-picture over van sensor.afvalinfo_gft als gft vandaag/morgen aan de beurt is).

```yaml
sensor:
  - platform: template
    sensors:
      afvalinfo_vandaag:
        friendly_name: Afvalinfo Vandaag
        value_template: "{{ states('sensor.afvalinfo_today') }}"
        attribute_templates:
          entity_picture: >-
            {% set today = states('sensor.afvalinfo_today') %}
            {% if today == 'none' %}
              /local/icons/kliko3.png
            {% else %}
              {{ state_attr('sensor.afvalinfo_' ~ today, 'entity_picture') }}
            {% endif %}
      afvalinfo_morgen:
        friendly_name: Afvalinfo Morgen
        value_template: "{{ states('sensor.afvalinfo_tomorrow') }}"
        attribute_templates:
          entity_picture: >-
            {% set today = states('sensor.afvalinfo_tomorrow') %}
            {% if today == 'none' %}
              /local/icons/kliko3.png
            {% else %}
              {{ state_attr('sensor.afvalinfo_' ~ today, 'entity_picture') }}
            {% endif %}
```

Met deze configuratie heb je naast `sensor.afvalinfo_today` dus een nieuwe `sensor.afvalinfo_vandaag` die dezelfde data weergeeft, maar tevens de entity_picture overneemt van de sensor die vandaag aan de beurt is (en datzelfde principe voor morgen/tomorrow)
