### ISSUE TITLE
Entities unavailable

### ISSUE THREAD

**Issue by Rikkie80** [heyajohnny/afvalinfo#184]
All of a sudden my Afvalinfo entities are not available anymore. Strange thing is that I don't get any log message...
Before it worked for at least a year without problems...
Also after restarting Home Assistant or my complete VM, no success...

I am still able to get the right information via afvalinfo.nl (not my address, but valid address for Veldhoven: 5503PN 15)

Configuration:
```
- platform: afvalinfo
  resources:
    - pbd
    - gft
    - papier
    - restafval
    - trash_type_today
  location: !secret afvalinfo_city
  postcode: !secret afvalinfo_postcode
  streetnumber: !secret afvalinfo_number
  dateformat: "%A %d %B"
  locale: "nl"
  timespanindays: 365
```
