### ISSUE TITLE
Alkmaar state unknown

### ISSUE THREAD

**Issue by Sjeff** [heyajohnny/afvalinfo#190]
Hi,

Can you please take a look at the Alkmaar api all the entities are unknown for a couple of weeks now.
![image](https://user-images.githubusercontent.com/11430228/112677393-f5b62f80-8e69-11eb-8b98-43d0d4f369ee.png)

**Comment by heyajohnny** [comment]
Hi, it works fine for this address: 1829XB 37 Alkmaar
If you can provide a postcode + streetnumber that isn't working, I can look into it.

**Comment by Sjeff** [comment]
This are the settings i use.
```
- platform: afvalinfo
  id: Stompetoren
  resources:
    - restafval
    - gft
    - papier
    - pbd
    - trash_type_today
    - trash_type_tomorrow
  postcode: 1841EP
  streetnumber: 19
```

**Comment by Sjeff** [comment]
> Hi, it works fine for this address: 1829XB 37 Alkmaar
> If you can provide a postcode + streetnumber that isn't working, I can look into it.

even with the information you provided i still get an unknown state:
```
- platform: afvalinfo
  id: Stompetoren
  resources:
    - gft
    - kerstboom
    - pbd
    - papier
    - restafval
    - textiel
    - trash_type_today
    - trash_type_tomorrow
  postcode: 1829XB
  streetnumber: 37
```
