### ISSUE TITLE
Provided template cant handle two collections on one day.

### ISSUE THREAD

**Issue by JBakers** [heyajohnny/afvalinfo#210]
Heya Johnny,

Integration works flawless, but the provided template at the end of the info, although it works, it can't handle two collections on one day.

`- platform: template
  sensors:
    afvalinfo_next_trash_type_and_date:
      value_template: >
        {% set ns = namespace(minimum=365) %}
        {% set list = ['gft', 'kerstboom', 'papier', 'pbd', 'restafval','textiel'] %}
        {%- for l in list %}
        {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
        {%- if days != None and days < ns.minimum %}
        {%- set ns.minimum = days %}
        {%- endif %}
        {%- endfor %}
        {%- for l in list %}
        {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
        {%- if days == ns.minimum %}
        {{l}} · {{ states('sensor.afvalinfo_' ~l) }}
        {%- endif %}
        {%- endfor %}`

For example, tomorrow, they'll be collecting gft and pbd and the template just add's them together in one line, making it impossible to read everything.

Thanks

**Comment by heyajohnny** [comment]
It shows the trash types seperated by a comma.

What do you mean with 'making it impossible to read everything'?

What are you trying to achieve?

**Comment by bafplus** [comment]
I use this card, maybe it suits you're need.
Its not the best probably but hey, it works ;-)

```
type: entity-filter
entities:
  - entity: sensor.afvalinfo_thuis_gft
    name: GFT
    icon: mdi:delete
  - entity: sensor.afvalinfo_thuis_kerstboom
    name: Kerstboom
    icon: mdi:pine-tree
  - entity: sensor.afvalinfo_thuis_pbd
    name: Plastic
    icon: mdi:bottle-soda-classic
  - entity: sensor.afvalinfo_thuis_papier
    name: Papier
    icon: mdi:package-variant
  - entity: sensor.afvalinfo_thuis_restafval
    name: Restafval
    icon: mdi:delete
  - entity: sensor.afvalinfo_thuis_textiel
    name: Textiel
    icon: mdi:tshirt-crew
state_filter:
  - operator: '=='
    value: false
    attribute: hidden
card:
  type: entities
  title: Afval
```
