### ISSUE TITLE
Avalex lijkt website aangepast te hebben met nieuwe url voor de kalender

### ISSUE THREAD

**Issue by Klapperman** [heyajohnny/afvalinfo#217]
De url is nu https://www.avalex.nl/kalender-kaart/. De oude url /kalender/ levert een 404 op. 
Momenteel werkt de integratie niet meer en zijn er geen data bekend en staat de volgende foutmelding in het log:

```
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.afvalinfo.const.const
Source: custom_components/afvalinfo/location/trashapi.py:58
Integration: afvalinfo (documentation, issues)
First occurred: 30 september 2021 20:52:09 (14 occurrences)
Last logged: 9:58:42

Error occurred. Please check the address with postcode: '2283CX' and huisnummer: '8' on the website of your local waste collector in the gemeente: 'rijswijk'. It's probably a faulty address or the website of the waste collector is unreachable. If the address is working on the website of the local waste collector and this error still occured, please report the issue in the Github repository https://github.com/heyajohnny/afvalinfo with details of the location that isn't working
```

Mijn huidige configuratie is:
```
# afvalinfo
- platform: afvalinfo
  resources:
    - restafval
    - gft
    - papier
    - trash_type_today
    - trash_type_tomorrow
  location: rijswijk
  postcode: 2283CX
  streetnumber: 8
  locale: "nl"
```
