### ISSUE TITLE
Cannot get any data

### ISSUE THREAD

**Issue by Remko76** [heyajohnny/afvalinfo#221]
I have installed your component and set up the configuration:

```
  - platform: afvalinfo
    resources:
      - gft
      - kerstboom
      - pbd
      - papier
      - restafval
      - textiel
      - trash_type_today
      - trash_type_tomorrow
    location: arnhem
    postcode: 6843EX
    streetnumber: 71
```

So far it works, all the sensor entities get created, but there is no data available. The status of everyone of the sensors is "unknown"

Is there anything I am missing here?
