### ISSUE TITLE
Please integrate a sensor that shows what trash is picked up tomorrow

### ISSUE THREAD

**Issue by martijndemulder** [heyajohnny/afvalinfo#24]
**Example:**
```
      afval_morgen:
		friendly_name: "Afval morgen"
        value_template: >
          {% if state_attr('sensor.afvalinfo_gft', 'days_until_collection_date') ==1 %}
            {{ state_attr('sensor.afvalinfo_gft', 'friendly_name') }}
          {% elif state_attr('sensor.afvalinfo_oud_papier', 'days_until_collection_date') ==1 %}
            {{ state_attr('sensor.afvalinfo_oud_papier', 'friendly_name') }}
          {% elif state_attr('sensor.afvalinfo_pbd', 'days_until_collection_date') ==1 %}
            {{ state_attr('sensor.afvalinfo_pbd', 'friendly_name') }}
          {% elif state_attr('sensor.afvalinfo_restafval', 'days_until_collection_date') ==1 %}
            {{ state_attr('sensor.afvalinfo_restafval', 'friendly_name') }}
          {% else %}
            Niets
          {% endif %}
```

With that, you can work with "state images" and generate something like: (based on the kind of trash that next)
![image](https://user-images.githubusercontent.com/60365040/75915603-28ece180-5e57-11ea-8da8-6dc126904697.png)

```
**Lovelace config:**
aspect_ratio: 60%
entities:
  - entity: sensor.afvalinfo_gft
  - entity: sensor.afvalinfo_oud_papier
  - entity: sensor.afvalinfo_pmd
  - entity: sensor.afvalinfo_restafval
```

**Comment by heyajohnny** [comment]
I'll add something like that. Also thinking about a sensor for today. So the sensors will be called:
-trash_type_today
-trash_type_tomorrow

The results of these sensors will be one of the following:
- gft
- papier
- pbd
- restafval
- textiel

I'll probably look into it in the coming week...

**Comment by ManCaveMedia** [comment]
I really like this option.
May I add a similar suggestion?
It would be great to me able to sort the icons on the lovelace cards by collection date.

For example:
The garbage and GFT in my area are being collected bi-weekly and paper once a month. (So, garbage one week, GFT the next week.)
I have a glance card that shows:
1. Garbage, 2. GFT, 3. Paper

Because GFT will be collected before the garbage is (from today), I would love for the order to be dynamically changed.
As far as I know it's not possible with conditional cards because we can't compare states, can we?

**Comment by martijndemulder** [comment]
I looked into that, but haven’t really found an option to suit that yet!
I think it should be possible…but how! The “easy” solution would probably involve some custom cards.
I’ll try to look into the possibility this weekend, maybe It’s possible!

Van: ManCaveMedia <notifications@github.com>
Verzonden: maandag 9 maart 2020 09:21
Aan: heyajohnny/afvalinfo <afvalinfo@noreply.github.com>
CC: martijndemulder <martijndemulder@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [heyajohnny/afvalinfo] Please integrate a sensor that shows what trash is picked up tomorrow (#24)


I really like this option.
May I add a similar suggestion?
It would be great to me able to sort the icons on the lovelace cards by collection date.

For example:
The garbage and GFT in my area are being collected bi-weekly and paper once a month. (So, garbage one week, GFT the next week.)
I have a glance card that shows:

  1.  Garbage, 2. GFT, 3. Paper

Because GFT will be collected before the garbage is (from today), I would love for the order to be dynamically changed.
As far as I know it's not possible with conditional cards because we can't compare states, can we?

**Comment by martijndemulder** [comment]
That would be great! And..(haven’t said it yet) but great work so far on the sensor! It looks great!

Van: heyajohnny <notifications@github.com>
Verzonden: zondag 8 maart 2020 16:17
Aan: heyajohnny/afvalinfo <afvalinfo@noreply.github.com>
CC: martijndemulder <martijndemulder@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [heyajohnny/afvalinfo] Please integrate a sensor that shows what trash is picked up tomorrow (#24)


I'll add something like that. Also thinking about a sensor for today. So the sensors will be called:
-trash_type_today
-trash_type_tomorrow

The results of these sensors will be one of the following:

  *   gft
  *   papier
  *   pbd
  *   restafval
  *   textiel

I'll probably look into it in the coming week...

**Comment by heyajohnny** [comment]
@martijndemulder 
I've pushed an update. It should be working now :)

Here is a complete list of special resources. To make these resources work, you also need to specify one or more of the normal resources from above.
So if you only specify -pbd and -trash_type_today under your resources, you will only get a result if the trash type 'pbd' has the same date as today.
These resources will return one or more (seperated with a space) of the following results (gft, papier, pbd, restafval, textiel).

- trash_type_today (only gives a result if minimal one of the normal resources dates is today)
- trash_type_tomorrow (only gives a result if minimal one of the normal resources dates is tomorrow)

**Comment by michelotten** [comment]
To sort the trashtypes based on pickup date I'm currently using the [auto-entities card](https://github.com/thomasloven/lovelace-auto-entities) with the following code in my ui-lovelace.yaml.
```
      - type: custom:auto-entities
        card:
          type: glance
        filter:
          include:
            - entity_id: sensor.afvalinfo_gft
              options:
                name: GFT
                image: /local/icons/gft_80.png
            - entity_id: sensor.afvalinfo_pbd
              options:
                name: PMD
                image: /local/icons/pmd_80.png
            - entity_id: sensor.afvalinfo_oud_papier
              options:
                name: Papier
                image: /local/icons/papier_80.png
        sort:
          attribute: days_until_collection_date
          method: attribute
          numeric: true
```
Giving the following result:
![Screenshot_20200311-212102~2](https://user-images.githubusercontent.com/6818628/76460456-50efbe00-63de-11ea-86ef-b261b2241cc8.jpg)
