### ISSUE TITLE
Having issue data unknown for "Land van Cuijk"

### ISSUE THREAD

**Issue by michelcs77** [heyajohnny/afvalinfo#255]
I have installed the latest version  0.9.0 (HACS). I don't understand whats wrong.

configuration file

- platform: afvalinfo
    resources:
      - gft
      - kerstboom
      - pbd
      - papier
      - restafval
      - textiel
      - trash_type_today
      - trash_type_tomorrow
    location: land van cuijk
    postcode: 5432BW
    streetnumber: _(delete for privacy reasons, normal housenumber)_
    streetnumbersuffix: ""
    dateformat: "%d-%m-%Y"
    locale: "nl"
    timespanindays: 365
  - platform: template
    sensors:
      paper_days_until_collection:
        value_template: "{{ state_attr('sensor.afvalinfo_papier', 'days_until_collection_date') }}"

  - platform: template
    sensors:
      afvalinfo_next_trash_type_and_date:
        value_template: >
          {% set ns = namespace(minimum=365) %}
          {% set list = ['gft', 'kerstboom', 'papier', 'pbd', 'restafval','textiel'] %}
          {%- for l in list %}
          {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
          {%- if days != None and days < ns.minimum %}
          {%- set ns.minimum = days %}
          {%- endif %}
          {%- endfor %}
          {%- for l in list %}
          {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
          {%- if days == ns.minimum %}
          {{l}} · {{ states('sensor.afvalinfo_' ~l) }}
          {%- endif %}
          {%- endfor %} 
          
       
![image](https://user-images.githubusercontent.com/83516214/151992130-ff3ca886-90ab-4964-b611-f818d4939e2d.png)
 
 
![image](https://user-images.githubusercontent.com/83516214/151992212-51356e0b-cb40-4540-a091-9577bdf577cb.png)

Also get a error in de "Vieze geit app"

**Comment by heyajohnny** [comment]
Hi, thnx for reaching out. I've tested it with 5432BW 1 and then I get the results I expected.
Results from afvalinfo:
![image](https://user-images.githubusercontent.com/20553716/152118680-8fee4c0b-9ad4-42de-bc57-2a40b7edfa11.png)
Results from the gemeente site:
![image](https://user-images.githubusercontent.com/20553716/152118526-0766166d-0300-43b6-9579-3df1d3cef0b7.png)

Maybe you can test your location @ [gemeentelandvancuijk](https://www.gemeentelandvancuijk.nl/afvalkalender/)

**Comment by michelcs77** [comment]
location: land van cuijk

must be: 
location: gemeentelandvancuijk

is that the solution

**Comment by heyajohnny** [comment]
No, location should be:
land van cuijk

Just tested it with this configuration:
```
- platform: afvalinfo
    resources:
      - gft
      - kerstboom
      - pbd
      - papier
      - restafval
      - takken
      - textiel
      - trash_type_today
      - trash_type_tomorrow
    location: land van cuijk
    postcode: 5432BW
    streetnumber: 1
    streetnumbersuffix: ""
    dateformat: "%d-%m-%Y"
    locale: "nl"
    timespanindays: 365
```
with this result:
![image](https://user-images.githubusercontent.com/20553716/152134839-611cf753-d562-4e89-b981-6563bdf3a7bb.png)

It should take a couple of seconds to update the data in HA. 
Dit you already tried a restart after changing the configuration?
