### ISSUE TITLE
Unable to verify configuration after adding sensor for afvalwijzer

### ISSUE THREAD

**Issue by lpwevers** [heyajohnny/afvalinfo#257]
Hi,

I'm trying to get 'afvalwijzer' to work. I installed the latest version using HACS and added the following to my configuration.yaml:
```
#  Afvalwijzer
sensor afvalwijzer:
  - platform: afvalinfo
    resources:
      - gft
      - kerstboom
      - pbd
      - papier
      - restafval
      - takken
      - textiel
      - trash_type_today
      - trash_type_tomorrow
    location: sittard-geleen
    postcode: 6161BW
    streetnumber: 194
    streetnumbersuffix: ""
    dateformat: "%d-%m-%Y"
    locale: "nl"
    timespanindays: 365
```

Then, from the GUI I navigate to Configuration -> Settings and click "Check configuration". That just never ends. Also, restarting HA from there just does nothing.

When I take out the configuration above from configuration.yaml all works again. Configuration is validated in a few seconds and restarting HA works.

I checked the logs, but can't find anything related to this issue. Please tell me what I'm doing wrong.

Kind regards,
Louis

**Comment by heyajohnny** [comment]
I've just copy pasted the configuration from above and it worked like a charm:
![image](https://user-images.githubusercontent.com/20553716/152532295-5735d1d5-5cf8-45c4-b227-64a24d053a35.png)

I really don't know what the problem could be... maybe some duplicate sensor names or something

**Comment by lpwevers** [comment]
Hi,

Thanks for testing. I did an update tot the new release you just put online and now, all of a sudden it works. Issue resolved.

**Comment by nielsheeren** [comment]
I have the same issue. Had it before and was trying it again with the new version but still cannot validate the configuration. I also tried with the config from this post and has the same issue.

**Comment by heyajohnny** [comment]
@nielsheeren try the [example configuration.yaml](https://github.com/heyajohnny/afvalinfo/blob/master/example/configuration.yaml)

**Comment by nielsheeren** [comment]
> @nielsheeren try the [example configuration.yaml](https://github.com/heyajohnny/afvalinfo/blob/master/example/configuration.yaml)

Had the same issue but I found the solution. It works only if you use a seperate `sensor:`  node for the afvalinfo sensor.

So this fails:

```
sensor:
  - platform: afvalinfo
    resources:
      - type: gft
        friendly_name: Groente Fruit en Tuinafval
      - type: kerstboom
        friendly_name: Kerstboom
      - type: pbd
        friendly_name: Plastic Blik en Drankkartons
      - type: papier
        friendly_name: Papier
      - type: restafval
        friendly_name: Restafval
      - type: takken
        friendly_name: Takken
      - type: textiel
        friendly_name: Oude Kleding
      - type: trash_type_today
        friendly_name: Afval voor vandaag
      - type: trash_type_tomorrow
        friendly_name: Afval voor morgen
    location: midden-drenthe
    postcode: 9423NA
    streetnumber: 1
    streetnumbersuffix: ""
    dateformat: "%d-%m-%Y"
    locale: "nl"
    timespanindays: 365

  - platform: systemmonitor
    resources:
      - type: processor_temperature
      - type: processor_use
```
and this works fine:

```
sensor:
  - platform: afvalinfo
    resources:
      - type: gft
        friendly_name: Groente Fruit en Tuinafval
      - type: kerstboom
        friendly_name: Kerstboom
      - type: pbd
        friendly_name: Plastic Blik en Drankkartons
      - type: papier
        friendly_name: Papier
      - type: restafval
        friendly_name: Restafval
      - type: takken
        friendly_name: Takken
      - type: textiel
        friendly_name: Oude Kleding
      - type: trash_type_today
        friendly_name: Afval voor vandaag
      - type: trash_type_tomorrow
        friendly_name: Afval voor morgen
    location: midden-drenthe
    postcode: 9423NA
    streetnumber: 1
    streetnumbersuffix: ""
    dateformat: "%d-%m-%Y"
    locale: "nl"
    timespanindays: 365

sensor:
  - platform: systemmonitor
    resources:
      - type: processor_temperature
      - type: processor_use
```
