### ISSUE TITLE
afvalinfo_next_trash_type_and_date lijkt niet goed te werken (bij mij iig)

### ISSUE THREAD

**Issue by robinwillems** [heyajohnny/afvalinfo#279]
Ik heb volgend probleem nog niet eerder gezien of gehad, maar mogelijk heeft iemand dit eerder gezien.

Ik heb namelijk dat afvalinfo_next_trash_type_and_date niet de eerstvolgende lediging aangeeft maar die van een ander, een paar dagen erop. Aankomend zou namelijk in onderstaande  schreenshot Plastic moeten zijn (31 maart) maar in plaats daarvan zegt hij dat papier de eerst volgende is (op 5 april)
![image](https://user-images.githubusercontent.com/6528318/160579301-577f34c9-d934-48cd-a7bb-2245eae648a6.png)

Gebruikte code in configuration.yaml:
```yaml
# Afval info App
sensor:
  - platform: afvalinfo
    resources:
      - type: pbd
        friendly_name: Plastic Blik en Drankpakken
      - type: gft
        friendly_name: Groente Fruit en Tuinafval
      - type: papier
        friendly_name: Papier
      - type: trash_type_today
        friendly_name: Afval voor vandaag
      - type: trash_type_tomorrow
        friendly_name: Afval voor morgen
    location: apeldoorn
    postcode: 7327da
    streetnumber: 118
    dateformat: '%a %d %b'
    locale: 'nl'
    timespanindays: 365
    notrashtext: 'geen'

  - platform: template
    sensors:
      afvalinfo_next_trash_type_and_date:
        unique_id: "Volgende container lediging"
        friendly_name: 'Volgende container lediging'
        value_template: >
          {% set ns = namespace(minimum=365) %}
          {% set list = ['gft', 'kerstboom', 'pbd', 'papier', 'restafval', 'takken', 'textiel'] %}
          {%- for l in list %}
          {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
          {%- if days != None and days < ns.minimum %}
          {%- set ns.minimum = days %}
          {%- endif %}
          {%- endfor %}
          {%- for l in list %}
          {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
          {%- if days == ns.minimum %}
          {{l}} · {{ states('sensor.afvalinfo_' ~l) }}
          {%- endif %}
          {%- endfor %}

  - platform: template
    sensors:
      paper_days_until_collection:
        unique_id: "Aantal dagen totdat het papier wordt gehaald"
        friendly_name: 'Aantal dagen totdat het papier wordt gehaald'
        value_template: "{{ state_attr('sensor.afvalinfo_papier', 'days_until_collection_date') }}"
 ```
