### ISSUE TITLE
2022-05-05 12:27:25 ERROR (SyncWorker_0) [custom_components.afvalinfo.const.const] Error occurred. Please check the address with postcode: '2361GB' and huisnummer: '3' on the website of your local waste collector in the gemeente: 'teylingen'.

### ISSUE THREAD

**Issue by bruvv** [heyajohnny/afvalinfo#288]
When using:
https://www.mijnafvalwijzer.nl/nl/2361GB/3/a001/
It works fine but when using:
```yaml
- platform: afvalinfo
  resources:
    - pbd
    - gft
    - papier
    - restafval
    - textiel
    - trash_type_today
    - trash_type_tomorrow
  location: Teylingen
  postcode: 2361GB
  streetnumber: 3
  streetnumbersuffix: a001
  locale: 'nl'
```
I get the error:
`2022-05-05 12:27:25 ERROR (SyncWorker_0) [custom_components.afvalinfo.const.const] Error occurred. Please check the address with postcode: '2361GB' and huisnummer: '3' on the website of your local waste collector in the gemeente: 'teylingen'.`
