### ISSUE TITLE
Werkt niet meer sinds 22.5.x ofzo

### ISSUE THREAD

**Issue by Qwyrp** [heyajohnny/afvalinfo#292]
Heeft altijd goed gewerkt maar sinds kort (22.5.2. ofzo) werkt Afvalinfo niet meer. Worden weergegeven als niet beschikbaar. Ik heb ook een andere gemeente ingevuld maar dat hielp ook niet.

**Comment by heyajohnny** [comment]
Misschien zijn de sensor namen veranderd? Dat schijnt bij enkele gebruikers weleens voor te komen.

**Comment by Qwyrp** [comment]
Die staan vlgs mij goed, hier een voorbeeld: **sensor.afvalinfo_gft**
Kan ik niet ergens een log aanzetten om te kijken of er ms ergens wat mis gaat?

**Comment by SilentScreamer1991** [comment]
Same here. Werkt al een behoorlijk aantal weken niet meer. Hij geeft unavailable aan voor alle sensors.

**Comment by lkeijser** [comment]
E.e.a. is gewijzigd. Ik had precies hetzelfde en heb daarop m'n configuration.yaml aangepast. Dit werkt voor mij:

```
  - platform: afvalinfo
    resources:                     #  (at least 1 required)
      - type: gft
        friendly_name: Groente Fruit en Tuinafval
      - type: papier
        friendly_name: Papier
      - type: restafval
        friendly_name: Restafval
      - type: trash_type_today
        friendly_name: Afval voor vandaag
      - type: trash_type_tomorrow
        friendly_name: Afval voor morgen
    location: rotterdam rozenburg           # (required, default = sliedrecht) name of the 'gemeente'
    postcode: 1234AB               #  (required, default = 3361AB)
    streetnumber: 1                #  (required, default = 1)
    #dateformat: '%d-%m-%Y'         #  (optional, default = %d-%m-%Y) day-month-year
    dateformat: '%a %d %b %Y'
    locale: 'nl'                   #  (optional, default = 'en')
    timespanindays: 365            #  (optional, default = 365) number of days to look into the future
```

Heb alleen even mijn postcode en huisnummer gewijzigd ;-)  Dan in m'n dashboard heb ik een kaartje met:

```
type: entities
entities:
  - entity: sensor.afvalinfo_groente_fruit_en_tuinafval
    icon: mdi:leaf
    name: Groente/Fruit/Tuin
  - entity: sensor.afvalinfo_papier
    name: Papier
  - entity: sensor.afvalinfo_restafval
    icon: mdi:trash-can
    name: Restafval
title: Afval ophaaldata
show_header_toggle: false
state_color: false
```
