### ISSUE TITLE
Error occurred. Please check the address with postcode 'xxx' and huisnummer 'xx'

### ISSUE THREAD

**Issue by bramstroker** [heyajohnny/afvalinfo#297]
When I check mijnafvalwijzer.nl the calendar is loaded correctly for my address.

```
Error occurred. Please check the address with postcode: '3911LA' and huisnummer: '17''B' on the website of your local waste collector in the gemeente: 'rhenen'. It's probably a faulty address or the website of the waste collector is unreachable. If the address is working on the website of the local waste collector and this error still occured, please report the issue in the Github repository https://github.com/heyajohnny/afvalinfo with details of the location that isn't working
```

**Comment by bramstroker** [comment]
Did some further debugging and got it working when I don't pass the `diftarcode`.
When I add it I get this exception.

I want to get access to the "afvalpunten gebruikt".
When I go to www.mijnafvalwijzer and menu "Afvalpunten verbruikt" I see a post request to the following endpoint.
https://www.mijnafvalwijzer.nl/site/diftarlogin

So I assumed I could use this code as diftarcode which was supplied to me by letter.

Let me know if I need to supply any further information. I can sent you my code through another channel (email) if this helps.

**Comment by heyajohnny** [comment]
I only had one test location to test the diftar, so your location might have different information. You could send the code to heyajohnny(at)hotmail(dot) com. But I'm on a small holiday right now, so I can't fix it right now.

**Comment by nicokars** [comment]
same problem as bramstoker.
postcode 1394JR 6  (wijdemeren is in the list)  and has always worked... and now...
Error occurred. Please check the address with postcode: 
1394JR
no changes i have made. 
perhaps it is a problem at mijnafvalwijzer site?

Afvalwijzer version: 1.07
Home Assistant Core 2022.6.5
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1
latest : Hacs
Integration version: | 1.25.5
Frontend version: | 20220529181005

**Comment by roosenbrug** [comment]
Same problem for 3402SR IJsselstein

**Comment by bafplus** [comment]
Same for Drimmelen 4844VP

**Comment by bafplus** [comment]
Even getest, gedowngrade naar 1.06 en alles werkt weer. Ik wacht de fix wel even af :-)

**Comment by nicokars** [comment]
Tja, dat ligt voor de hand, ware het niet dat ik deze niet meer heb.
Heb jij een link of kan je hem opsturen via wetransfer misschien
Alvast bedankt,
Gr Nico

**Comment by bafplus** [comment]
Simpelweg naar HACS->integraties->afvalinfo gaan en op de 3 bolletjes rechtsonder klikken. Dan op "opnieuw downloaden" klikken. Daar zie je een dropdownlijst met alle versies (even paar sec wachten tot deze van grijs naar wit kleurt) en daar versie 1.0.6 selecteren. Dan wordt de vorige versie gedownload en geinstalleerd, waarna je HA moet herstarten.

Let wel op! Je krijgt dan wel weer de melding dat er een nieuwe versie (1.0.7) is! Deze voor nu even negeren tot versie 1.0.8 beschikbaar is met de fix.

**Comment by nicokars** [comment]
Bedankt voor de oplossing.
Alle info werkt nu weer

M.vr.gr.

Nico Karssemeijer


Op 16 jun. 2022 om 16:20 heeft bafplus ***@***.***> het volgende geschreven:

﻿

Simpelweg naar HACS->integraties->afvalinfo gaan en op de 3 bolletjes rechtsonder klikken. Dan op "opnieuw downloaden" klikken. Daar zie je een dropdownlijst met alle versies (even paar sec wachten tot deze van grijs naar wit kleurt) en daar versie 1.0.6 selecteren. Dan wordt de vorige versie gedownload en geinstalleerd, waarna je HA moet herstarten.

Let wel op! Je krijgt dan wel weer de melding dat er een nieuwe versie (1.0.7) is! Deze voor nu even negeren tot versie 1.0.8 beschikbaar is met de fix.

**Comment by heyajohnny** [comment]
@nicokars 
Je adres werkt prima met de laatste Afvalinfo versie op Home Assistant Core 2022.7.0.dev0
```
sensor:
  - platform: afvalinfo
    resources:
      - type: pbd
        friendly_name: Plastic Blik en Drankpakken
      - type: gft
        friendly_name: Groente Fruit en Tuinafval
      - type: papier
        friendly_name: Papier
      - type: restafval
        friendly_name: Restafval
      - type: trash_type_today
        friendly_name: Afval voor vandaag
      - type: trash_type_tomorrow
        friendly_name: Afval voor morgen
    location: wijdemeren
    postcode: 1394JR
    streetnumber: 6
    dateformat: '%a %d %b'
    locale: 'nl'
    timespanindays: 365
    notrashtext: 'geen'
```
![image](https://user-images.githubusercontent.com/20553716/174433840-3e933890-5b0c-42aa-a54e-bf7abbdca81e.png)
