### ISSUE TITLE
Gemeente Haarlem/Spaarnelanden werkt niet

### ISSUE THREAD

**Issue by mrtnbr** [heyajohnny/afvalinfo#303]
Al enige tijd krijg ik geen informatie meer via afvalinfo over de ophaaldagen. Dit is mijn aangepast configuratie.

```
- platform: afvalinfo
  resources:
    - pbd
    - gft
    - trash_type_today
    - trash_type_tomorrow
  location: haarlem 
  postcode: 2024TJ  
  streetnumber: 12 
  locale: 'nl'
```

Als ik de configuratie naar de defaults aanpast krijg ik wel informatie.

Home Assistant versies: 2022.6.x en 2022.7.0.dev20220627 geprobeerd.
Afvalinfo versies: 1.0.7, 1.0.6 en 1.05 geprobeerd.

Ik zie niks in de logs. (loglevel debug & error geprobeerd).

Op https://afvalwijzer.spaarnelanden.nl/ krijg ik wel resultaat.
