### ISSUE TITLE
helpppppppp

### ISSUE THREAD

**Issue by CorKevenaar** [heyajohnny/afvalinfo#304]
Sorry maar ben zo bleu als het maar  kan op HA gebied, maar loop even vast op dit gebied.
ik wilde de afvalinfo instaleren en loop dan even ast, ik hoop dat iemand mij even op weg  kan helpen.
Wat heb ik gedaan:

- ik ben naar Hacs gegaan (ja die had ik al geinstaleerd) en heb daar de Afvalinfo gevonden.
- geinstalleerd
- daarna systeem gereboot
- bij intergraties van hacs zie ik hem ook staan
- als ik in HA naar intergraties toevoegen ga zie ikhem niet staan 

wat doe ik fout ??

**Comment by Squixx** [comment]
Je moet deze toevoegen via de configuration.yaml. Dit is nog niet mogelijk via de UI

**Comment by CorKevenaar** [comment]
### top een stap verder
kun je deze nitwit uit  leggen hoe en wat ik moet doen :)

**Comment by Squixx** [comment]
configuration.yaml openen:

```
sensor:
  - platform: afvalinfo
    resources:
      - gft
      - pbd
      - papier
      - restafval
      - kerstboom
      - takken
      - trash_type_today
      - trash_type_tomorrow
    location: <aanvullen>
    postcode: <aanvullen>
    streetnumber: <aanvullen>
    locale: "nl"
    notrashtext: "geen"
```

dit toevoegen (aanvullen waar nodig)

homeassistant herstarten.



https://siytek.com/home-assistant-configuration-yaml-beginners-guide/

mocht je _geen_ raspberry pi gebruiken als host.. kan je ook de visual studio code plugin gebruiken. Die heeft net een wat betere auto complete

**Comment by CorKevenaar** [comment]
Wel gelukt om hem te starten, maar nu geeft hij gene data weer ☹

nog tips

 

Van: Squixx ***@***.***> 
Verzonden: maandag 4 juli 2022 12:46
Aan: heyajohnny/afvalinfo ***@***.***>
CC: Cor Kevenaar ***@***.***>; Author ***@***.***>
Onderwerp: Re: [heyajohnny/afvalinfo] helpppppppp (Issue #304)

 

configuration.yaml openen:

sensor:
  - platform: afvalinfo
    resources:
      - gft
      - pbd
      - papier
      - restafval
      - kerstboom
      - takken
      - trash_type_today
      - trash_type_tomorrow
    location: <aanvullen>
    postcode: <aanvullen>
    streetnumber: <aanvullen>
    locale: "nl"
    notrashtext: "geen"

dit toevoegen (aanvullen waar nodig)

homeassistant herstarten.

https://siytek.com/home-assistant-configuration-yaml-beginners-guide/

mocht je geen raspberry pi gebruiken als host.. kan je ook de visual studio code plugin gebruiken. Die heeft net een wat betere auto complete

**Comment by CorKevenaar** [comment]
![image](https://user-images.githubusercontent.com/88622364/177166440-9f4464b2-db87-449a-9608-3f693a2e7129.png)
dit is wat ik zie

**Comment by Squixx** [comment]
Heb je je postcode en huisnummer aangepast?

**Comment by CorKevenaar** [comment]
Ja zker zo staat hij er in 

sensor:

  - platform: afvalinfo

    resources:

      - gft

      - pbd

      - papier

      - restafval

      - kerstboom

      - takken

      - trash_type_today

      - trash_type_tomorrow

    location: <doetinchem>

    postcode: <7006HT>

    streetnumber: <162>

    locale: "nl"

    notrashtext: "geen"

 

Van: Squixx ***@***.***> 
Verzonden: dinsdag 5 juli 2022 21:17
Aan: heyajohnny/afvalinfo ***@***.***>
CC: Cor Kevenaar ***@***.***>; Author ***@***.***>
Onderwerp: Re: [heyajohnny/afvalinfo] helpppppppp (Issue #304)

 

Heb je je postcode en huisnummer aangepast?

**Comment by Squixx** [comment]
```
    location: <doetinchem>

    postcode: <7006HT>

    streetnumber: <162>
```

even aanpassen naar

```
    location: "doetinchem"

    postcode: "7006HT"

    streetnumber: 162
```

**Comment by heyajohnny** [comment]
@CorKevenaar Ik neem aan dat deze ondertussen werkt? Zo niet, dan kan ik dit issue weer openen, maar voor nu sluit ik hem...

**Comment by CorKevenaar** [comment]
Sorry zaten midden in verbouwing hier, wijnig andere zaken gedaan :(

maar het probleem is er nog steeds   :(

**Comment by heyajohnny** [comment]
Maak anders eens een screenshot van het afvalinfo gedeelte van de configuration.yaml. Wellicht staat er een tabje oid verkeerd

**Comment by CorKevenaar** [comment]
Komt  goed, vanmiddag komt eerst mijn nieuwe NUC binnen wil daar HA op gaan zetten, als hij draaid gaan we kijken of het probleem er dan nog is, anders laat ik het weten, of het werkt of is opgelost.

Ps dank voor je vasthoudenheid om mij te helpen

**Comment by CorKevenaar** [comment]
zo nuc draaid nu, maar heb de backup daar terug gezet, en probleem is dus nog het zelfde.
ik zal hem hier even in plakken onder de streep

------------------------------------------------------

# Loads default set of integrations. Do not remove.
default_config:
sensor:

  - platform: afvalinfo

    resources:

      - gft

      - pbd

      - papier

      - restafval

      - kerstboom

      - takken

      - trash_type_today

      - trash_type_tomorrow

    location: "doetinchem"

    postcode: "7006HT"

    streetnumber: "162"

    locale: "nl"

    notrashtext: "geen"



# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


------------------------------------------------
dit is de hele yaml

**Comment by heyajohnny** [comment]
Pas hem eens aan naar dit:
```
default_config:
sensor:

  - platform: afvalinfo
    resources:
      - type: gft
        friendly_name: Groente Fruit en Tuinafval
      - type: pbd
        friendly_name: Plastic Blik en Drankpakken
      - type: papier
        friendly_name: Papier
      - type: restafval
        friendly_name: Restafval
      - type: kerstboom
        friendly_name: Kerstboom
      - type: takken
        friendly_name: Takken
      - type: trash_type_today
        friendly_name: Afval voor vandaag
      - type: trash_type_tomorrow
        friendly_name: Afval voor morgen
    location: "doetinchem"
    postcode: "7006HT"
    streetnumber: "162"
    locale: "nl"
    notrashtext: "geen"
```
(Hier nog een screenshot van de configuration.yaml)
![image](https://user-images.githubusercontent.com/20553716/182016284-f6d6f57f-987d-46f3-bea3-97f4d6a88232.png)
Dit geeft bij mij het volgende resultaat:
![image](https://user-images.githubusercontent.com/20553716/182016371-79f3e9fb-71a6-48d9-a7ae-cec97cecb66c.png)
