### ISSUE TITLE
"Error occured - please check" etc voor Maashorst op restafval ophaaldag

### ISSUE THREAD

**Issue by hmmbob** [heyajohnny/afvalinfo#306]
Sinds de upgrade naar 2022.7 vanochtend zijn alle afval sensoren unavailable. Het vreemde is dat gisteren, toen ik nog op de beta 2022.7.0.b5 zat, alles prima was.... 🤷🏻 

```yaml
##########################
## Trash sensors
##########################
- platform: afvalinfo
  resources:
    - gft
    - papier
    - pbd
    - restafval
    - trash_type_today
    - trash_type_tomorrow
  location: !secret afvalinfo_location
  postcode: !secret afvalinfo_postcode
  streetnumber: !secret afvalinfo_streetnumber
  locale: "nl"
```

```
Error occurred. Please check the address with postcode: '5403..' and huisnummer: '...''' on the website of your local waste collector in the gemeente: 'maashorst'. It's probably a faulty address or the website of the waste collector is unreachable. If the address is working on the website of the local waste collector and this error still occured, please report the issue in the Github repository https://github.com/heyajohnny/afvalinfo with details of the location that isn't working
```

Ik denk dat je mijn postcode en hn nog ergens zou kunnen hebben dankzij eerder debugwerk, anders kan ik het via discord oid wel even DM'en. Afvalkalender van de gemeente werkt gewoon prima.

edit: sterker nog, als ik de settings wijzig naar 5402AH 1 (die heb je eerder gebruikt bij de samenvoeging van Uden en Landerd in Maashorst), dan werkt het wél. Het is dus iets specifieks met mijn postcode en hn.

edit2: heb de broncode van de html pagina's van beide adressen vergeleken; anders dan verschillende data zie ik geen verschil...
