### ISSUE TITLE
Configuration.yaml issue

### ISSUE THREAD

**Issue by Corsw** [heyajohnny/afvalinfo#309]
Het is waarschijnlijk iets heel simpels, maar ik krijg de code niet goed voor elkaar in de configuration.yaml. In de logboeken komen de volgende meldingen terug:

```
2022-07-14 14:06:44 ERROR (MainThread) [homeassistant.config] Invalid config for [template]: [platform] is an invalid option for [template]. Check: template->platform. (See /config/configuration.yaml, line 44).
2022-07-14 14:06:44 ERROR (MainThread) [homeassistant.config] Invalid config for [template]: [platform] is an invalid option for [template]. Check: template->platform. (See /config/configuration.yaml, line 73).
2022-07-14 14:06:44 ERROR (MainThread) [homeassistant.config] Invalid config for [template]: [platform] is an invalid option for [template]. Check: template->platform. (See /config/configuration.yaml, line 78).
```

Mijn configuration.yaml ziet er als volgt uit:

```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
frontend:
  themes: !include_dir_merge_named themes
  
#Buienalarm integratie via HACS

sensor:
  - platform: buienalarm
    timeframe: 15
    name: buienalarm
    monitored_conditions:
      - temperature
      - precipitation
      - precipitation_forecast_average
      - precipitation_forecast_total
      - next_rain_forecast

#Buienalarm sensor voor aantal minuten tot regen

template:
  - sensor:
    - name: "Buienalarm Next rain forecast (min)"
      unit_of_measurement: "min"
      state: >
        {% if as_timestamp(states('sensor.buienalarm_next_rain_forecast')) %}
          {{ ( ( as_timestamp(states('sensor.buienalarm_next_rain_forecast')) - as_timestamp(now()) ) / 60 ) | round }}
        {% else %}
          {{ states('nonexistent') }}
        {% endif %}

  
# Afvalinfo HACS integratie 

  - platform: afvalinfo
    resources:
      - type: gft
        friendly_name: Groente Fruit en Tuinafval
      - type: kerstboom
        friendly_name: Kerstboom
      - type: pbd
        friendly_name: Plastic Blik en Drankkartons
      - type: papier
        friendly_name: Papier
      - type: restafval
        friendly_name: Restafval
      - type: takken
        friendly_name: Takken
      - type: textiel
        friendly_name: Oude Kleding
      - type: trash_type_today
        friendly_name: Afval voor vandaag
      - type: trash_type_tomorrow
        friendly_name: Afval voor morgen
    diftarcode: ""
    location: xxxxxxxxxx
    postcode: xxxxxx
    streetnumber: 1
    streetnumbersuffix: ""
    dateformat: "%d-%m-%Y"
    locale: "nl"
    timespanindays: 365
    notrashtext: "geen"
  - platform: template
    sensors:
      paper_days_until_collection:
        value_template: "{{ state_attr('sensor.afvalinfo_papier', 'days_until_collection_date') }}"

  - platform: template
    sensors:
      afvalinfo_next_trash_type_and_date:
        value_template: >
          {% set ns = namespace(minimum=365) %}
          {% set list = ['groente_fruit_en_tuinafval', 'kerstboom', 'plastic_blik_en_drankkartons', 'papier', 'restafval', 'takken', 'oude_kleding'] %}
          {% set friendly_list = ['Groente Fruit en Tuinafval', 'Kerstboom', 'Plastic Blik en Drankkartons', 'Papier', 'Restafval', 'Takken', 'Oude Kleding'] %}
          {%- for l in list %}
          {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
          {%- if days != None and days < ns.minimum %}
          {%- set ns.minimum = days %}
          {%- endif %}
          {%- endfor %}
          {%- for l in list %}
          {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
          {%- if days == ns.minimum %}
          {{friendly_list[loop.index0]}} · {{ states('sensor.afvalinfo_' ~l) }}
          {%- endif %}
          {%- endfor %}
```

Wat doe ik verkeerd?
