### ISSUE TITLE
Avalex site werkt, maar Afvalinfo geeft foutmelding

### ISSUE THREAD

**Issue by Klapperman** [heyajohnny/afvalinfo#314]
Avalex website werkt naar behoren. Maar in Home Assistant fout in het log en geen informatie.

Betreffende fout in het log:

```
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.afvalinfo.const.const
Source: custom_components/afvalinfo/location/trashapi.py:75
Integration: afvalinfo (documentation, issues)
First occurred: 00:47:04 (6 occurrences)
Last logged: 05:48:35

Error occurred. Please check the address with postcode: '2283CX' and huisnummer: '8''' on the website of your local waste collector in the gemeente: 'rijswijk'. It's probably a faulty address or the website of the waste collector is unreachable. If the address is working on the website of the local waste collector and this error still occured, please report the issue in the Github repository https://github.com/heyajohnny/afvalinfo with details of the location that isn't working
```

Configuratie in sensors.yaml
```
# afvalinfo
- platform: afvalinfo
  resources:
    - type: gft
      friendly_name: Groente Fruit en Tuinafval
    - type: papier
      friendly_name: Papier
    - type: restafval
      friendly_name: Restafval
    - type: trash_type_today
      friendly_name: Afval voor vandaag
    - type: trash_type_tomorrow
      friendly_name: Afval voor morgen
  location: rijswijk
  postcode: 2283CX
  streetnumber: 8
  locale: "nl"
```
