### ISSUE TITLE
Gemeente Westerkwartier werkt niet meer

### ISSUE THREAD

**Issue by sicco92** [heyajohnny/afvalinfo#315]
De gemeente Westerkwartier werkt niet meer goed. Ik krijg nu regelmatig deze errors. Af en toe werkt het ineens weer, maar de integratie werkt vaker niet dan wel.

> Logger: custom_components.afvalinfo.const.const
> Source: custom_components/afvalinfo/location/trashapi.py:75
> Integration: afvalinfo ([documentation](https://github.com/heyajohnny/afvalinfo), [issues](https://github.com/heyajohnny/afvalinfo/issues))
> First occurred: 15:58:42 (1 occurrences)
> Last logged: 15:58:42
> 
> Error occurred. Please check the address with postcode: '9351le' and huisnummer: '123''' on the website of your local waste collector in the gemeente: 'westerkwartier'. It's probably a faulty address or the website of the waste collector is unreachable. If the address is working on the website of the local waste collector and this error still occured, please report the issue in the Github repository https://github.com/heyajohnny/afvalinfo with details of the location that isn't working

Op de [website](https://www.westerkwartier.nl/afvalkalender) van gemeente Westerkwartier wordt doorgelinkt naar MijnAfvalwijzer, en daar werkt het wel: https://www.mijnafvalwijzer.nl/nl/9351le/123/

Dit is mijn configuratie:
```
- platform: afvalinfo
  resources:
    - type: gft
      friendly_name: GFT
    - type: kerstboom
      friendly_name: Kerstboom
    - type: pbd
      friendly_name: Plastic Blik en Drankpakken
    - type: papier
      friendly_name: Papier
    - type: restafval
      friendly_name: Restafval
    - type: textiel
      friendly_name: Textiel
    - type: trash_type_today
      friendly_name: Afval vandaag
    - type: trash_type_tomorrow
      friendly_name: Afval morgen
  location: westerkwartier
  postcode: 9351le
  streetnumber: 123
```
Ik ben net terug gegaan naar versie 1.06 en die lijkt vooralsnog wel goed te werken.

Als ik verder nog ergens bij kan helpen, dan hoor ik dat graag!
