### ISSUE TITLE
Gemeente Ouder Amstel

### ISSUE THREAD

**Issue by filmgarage** [heyajohnny/afvalinfo#325]
Is het mogelijk de gemeente Ouder-Amstel toe te voegen?
Ik heb geen idee of ze een methode bieden om deze data te verkrijgen
www.ouder-amstel.nl

**Comment by heyajohnny** [comment]
Ik ga deze gemeente meenemen bij de implementatie van #327

**Comment by heyajohnny** [comment]
@filmgarage Ik heb zojuist Ouder-Amstel toegevoegd. Laat maar weten of alles werkt zoals verwacht

**Comment by heyajohnny** [comment]
Ik sluit het issue. Mocht het toch niet goed werken, dan kan het altijd weer geopend worden

**Comment by filmgarage** [comment]
Ik heb geprobeerd om hem in te stellen maar mijn config check werkt niet meer als ik de yaml config in mijn configaration.yaml zet. Kan ik dan toch nog veilig HA herstarten?

**Comment by heyajohnny** [comment]
Nee, doe maar niet herstarten. Kun je je config hier plaatsen. In ieder geval de config voor afvalinfo. Wellicht dat ik kan zien wat er fout is.

**Comment by filmgarage** [comment]
Ik heb de code laten genereren op [de 4fv4l site](https://4fv4l.nl/ha)

Grappig is dat de postcode er bij wordt ingevuld als je eerst de postcode invoert en daarna pas voor "Ouder-Amstel" kiest. Maar het werkt bij mij niet met én zonder postcode...

```
sensor:
  - platform: afvalinfo
    id: Afval Duivendrecht
    resources:
      - type: gft
        friendly_name: GFT
      - type: kerstboom
        friendly_name: Kerstboom
      - type: pbd
        friendly_name: Pbd
      - type: papier
        friendly_name: Papier
      - type: restafval
        friendly_name: Restafval
      - type: trash_type_today
        friendly_name: Afval vandaag
      - type: trash_type_tomorrow
        friendly_name: Afval morgen
    location: Ouder-Amstel
    postcode: ''
    streetnumber: ''
    streetnumbersuffix: ''
    district: Bebouwde kom
    diftarcode: ''
    dateformat: '%d-%m-%Y'
    locale: nl
    timespanindays: 365
    notrashtext: geen
    getwholeyear: false
```
