### ISSUE TITLE
Afvalinfo werkt niet meer

### ISSUE THREAD

**Issue by droeloe1818** [heyajohnny/afvalinfo#337]
Hoi,

Ik krijg Afvalinfo niet meer aan de praat.
Als ik bij de sensor informatie kijk is die Unavailable en krijg ik de volgende melding: This entity is no longer being provided by the afvalinfo integration. If the entity is no longer in use, delete it in settings.

dit heb in de configuration.yaml staan:

```
sensor:
  - platform: afvalinfo
    resources:
      - type: gft
        friendly_name: Groente Fruit en Tuinafval
      - type: kerstboom
        friendly_name: Kerstboom
      - type: pbd
        friendly_name: Plastic Blik en Drankkartons
      - type: papier
        friendly_name: Papier
      - type: restafval
        friendly_name: Restafval
      - type: takken
        friendly_name: Takken
      - type: textiel
        friendly_name: Oude Kleding
      - type: trash_type_today
        friendly_name: Afval voor vandaag
      - type: trash_type_tomorrow
        friendly_name: Afval voor morgen
    diftarcode: ""
    location: sliedrecht
    postcode: 3361AB
    streetnumber: 1
    streetnumbersuffix: ""
    dateformat: "%d-%m-%Y"
    locale: "nl"
    timespanindays: 365
    notrashtext: "geen"
  - platform: template
    sensors:
      paper_days_until_collection:
        value_template: "{{ state_attr('sensor.afvalinfo_papier', 'days_until_collection_date') }}"
      
  - platform: template
    sensors:
      afvalinfo_next_trash_type_and_date:
        value_template: >
          {% set ns = namespace(minimum=365) %}
          {% set list = ['groente_fruit_en_tuinafval', 'kerstboom', 'plastic_blik_en_drankkartons', 'papier', 'restafval', 'takken', 'oude_kleding'] %}
          {% set friendly_list = ['Groente Fruit en Tuinafval', 'Kerstboom', 'Plastic Blik en Drankkartons', 'Papier', 'Restafval', 'Takken', 'Oude Kleding'] %}
          {%- for l in list %}
          {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
          {%- if days != None and days < ns.minimum %}
          {%- set ns.minimum = days %}
          {%- endif %}
          {%- endfor %}
          {%- for l in list %}
          {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
          {%- if days == ns.minimum %}
          {{friendly_list[loop.index0]}} · {{ states('sensor.afvalinfo_' ~l) }}
          {%- endif %}
          {%- endfor %}
```

Heb het adres aangepast naar het default adres om te kijken of het aan mijn adres lag maar dit is niet het geval.

ik heb ook de add-on opnieuw gedownload en gezet in  config\custom_components\afvalinfo

Ik ben zelf een beginner op het gebied van HA maar ik ben nu al 2 dagen bezig deze add-on  werkend te krijgen.

Wat doe ik fout?

Thanks!
