### ISSUE TITLE
PBD sensor voor Maashorst stuk

### ISSUE THREAD

**Issue by hmmbob** [heyajohnny/afvalinfo#360]
De PBD sensoren doen niets meer:
![image](https://user-images.githubusercontent.com/33529490/217750612-d7af9a74-5d09-4bad-99f7-c87003adfee0.png)

terwijl de afvalapp (bron) de gegevens nog wel heeft:
![image](https://user-images.githubusercontent.com/33529490/217750714-540300fe-de9a-4c3c-a444-5b0e4a185e49.png)

Betreft 2 adressen in 2 verschillende wijken btw

**Comment by heyajohnny** [comment]
@hmmbob Dank je voor het melden. Ze blijven maar dingen aanpassen bij DeAfvalApp :unamused:
Ik heb de selectie nu wat ruimer gemaakt. Het zou nu alleen nog kapot kunnen gaan als ze echt compleet andere naamgevingen gaan gebruiken. Als het goed is moet de PBD sensor weer werken. Zou je ook kunnen kijken of de andere sensoren ook nog werken, hierbij heb ik namelijk ook de ruimere selectie toegepast. Alvast bedankt!

**Comment by hmmbob** [comment]
Alles lijkt nu goed te gaan!

Ander ding: het lijkt erop dat deze sensoren niet "geforceerd" geupdate kunnen worden met de `homeassistant.update_entity` service?

```yaml
service: homeassistant.update_entity
data: {}
target:
  entity_id:
    - sensor.afvalinfo_pbd
    - sensor.afvalinfo_nieuwe_huis_pbd
    - sensor.afvalinfo_nieuwe_huis_gft
```

Geen van deze entiteiten kreeg een bijgewerkte `last_update` attribute (of gewijzigde value). Na een reboot wel.
