### ISSUE TITLE
Adding dates to Local Calander

### ISSUE THREAD

**Issue by xtrmenl** [heyajohnny/afvalinfo#372]
Said i would come back if i figured out how to get the Afval info dates in the home assistant 
and got it working for the next pickup 

first install via HACS 
https://github.com/gadgetchnnel/entities_calendar

restart HA

then add my code to configuration.yaml

```
calendar:
  platform: entities_calendar
  calendars:
    name: Omrin Afval
    entities:
      - entity: sensor.gft
        name: GFT
        start_time:
           timestamp_attribute: year_month_day_date
      - entity: sensor.kerstboom
        name: Kerstboom
        start_time:
           timestamp_attribute: year_month_day_date
      - entity: sensor.papier
        name: Papier
        start_time:
           timestamp_attribute: year_month_day_date        
      - entity: sensor.pbd
        name: Plastic
        start_time:
           timestamp_attribute: year_month_day_date
      - entity: sensor.restafval
        name: Rest
        start_time:
           timestamp_attribute: year_month_day_date
      - entity: sensor.textiel
        name: Textiel
        start_time:
           timestamp_attribute: year_month_day_date
```

and it will show up as the Omrin Afval Calander  (change omrin to name name you wish
https://i.imgur.com/ActWkuj.png
