### ISSUE TITLE
Homeassistant verwerkt de integratie niet (meer)

### ISSUE THREAD

**Issue by jvrossum** [heyajohnny/afvalinfo#389]
YAML config line van https://4fv4l.nl/ voor de gemeente Almere gebruikt, echter werkt deze niet ondanks dat de HACS integratie aanwezig is.

Herinstallatie van de integratie verhelpt het probleem niet.

"Deze entiteit is niet meer beschikbaar vanuit de afvalinfo integratie. Wanneer de entiteit niet meer in gebruik is, kan deze vanuit de instellingen verwijderd worden."

**Comment by heyajohnny** [comment]
Zou je wellicht je config hier kunnen posten. (Huisnummer kun je weghalen ivm privacy)

**Comment by Oulewappeur** [comment]
Ik heb precies dezelfde melding, er wordt bij mij opeens een extra "rest" sensor aangemaakt die niks rapporteert, terwijl er ook gewoon een restafval is. Ik heb mijn configuratie ook niet aangepast sinds dit probleem er is, voorheen werkte het prima!

**Comment by heyajohnny** [comment]
@Oulewappeur Is dit ineens gebeurd, of na een update van Home Assistant? Welke HA versie gebruik je?

**Comment by Oulewappeur** [comment]
@heyajohnny ik dacht in eerste instantie dat het aan 2023.9.0 lag, maar heb ook terug gedraaid naar 2023.8.4 en kwam daar tegen hetzelfde euvel.

![image](https://github.com/heyajohnny/afvalinfo/assets/36342485/3e44e870-56f0-420f-b49f-55fb3babd0e4)

![image](https://github.com/heyajohnny/afvalinfo/assets/36342485/b8f11d8d-b6a0-4de9-85fc-226077d6d072)

**Comment by Oulewappeur** [comment]
Ik heb voor het weekend de integratie en zojuist weer opnieuw toegevoegd en het lijkt nu weer te werken voor mij.

**Comment by heyajohnny** [comment]
Ik heb vanochtend een update gedaan van mijn eigen Home Assistant, maar ondervind niet de bovenstaande problemen...

**Comment by jvrossum** [comment]
```
sensor:
  - platform: afvalinfo
    id: Almere
    resources:
      - type: gft
        friendly_name: GFT
      - type: pbd
        friendly_name: PBD
      - type: papier
        friendly_name: Papier
      - type: restafval
        friendly_name: Restafval
      - type: trash_type_today
        friendly_name: Afval vandaag
      - type: trash_type_tomorrow
        friendly_name: Afval morgen
    location: Almere
    postcode: 0000XX
    streetnumber: '00'
    streetnumbersuffix: ''
    district: ''
    diftarcode: ''
    dateformat: '%d-%m-%Y'
    locale: nl
    notrashtext: geen
    getwholeyear: false
```
