### ISSUE TITLE
Sensoren worden niet toegevoegd

### ISSUE THREAD

**Issue by CoenvanderWind** [heyajohnny/afvalinfo#391]
Hallo, ik ben behoorlijk nieuw bij HA dus heb vast iets doms gedaan...

Ik heb alles toegevoegd volgens de stappen, maar ik krijg de entities niet in HA, heb alleen de update maar geen afval sensoren, kan je me helpen?

Mijn configurations.yaml:

- sensor:
  - platform: afvalinfo
    resources:
      #- type: cleanprofsgft
      #  friendly_name: Reiniging Gft
      #- type: cleanprofsrestafval
      #  friendly_name: Reiniging Restafval
      - type: gft
        friendly_name: Groente Fruit en Tuinafval
      - type: pbd
        friendly_name: Plastic Blik en Drankkartons
      - type: restafval
        friendly_name: Restafval
      - type: textiel
        friendly_name: Oude Kleding
      - type: trash_type_today
        friendly_name: Afval voor vandaag
      - type: trash_type_tomorrow
        friendly_name: Afval voor morgen
    diftarcode: ""
    location: stadskanaal
    postcode: 9591AX
    streetnumber: 4
    streetnumbersuffix: ""
    district: ""
    dateformat: "%d-%m-%Y"
    locale: "nl"
    notrashtext: "geen"
    getwholeyear: false
  - platform: template
    sensors:
      paper_days_until_collection:
        value_template: "{{ state_attr('sensor.afvalinfo_papier', 'days_until_collection_date') }}"

  - platform: template
    sensors:
      afvalinfo_next_trash_type_and_date:
        value_template: >
          {% set ns = namespace(minimum=365) %}
          {% set list = ['groente_fruit_en_tuinafval', 'kerstboom', 'plastic_blik_en_drankkartons', 'papier', 'restafval', 'takken', 'oude_kleding'] %}
          {% set friendly_list = ['Groente Fruit en Tuinafval', 'Kerstboom', 'Plastic Blik en Drankkartons', 'Papier', 'Restafval', 'Takken', 'Oude Kleding'] %}
          {%- for l in list %}
          {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
          {%- if days != None and days < ns.minimum %}
          {%- set ns.minimum = days %}
          {%- endif %}
          {%- endfor %}
          {%- for l in list %}
          {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
          {%- if days == ns.minimum %}
          {{friendly_list[loop.index0]}} · {{ states('sensor.afvalinfo_' ~l) }}
          {%- endif %}
          {%- endfor %}

**Comment by heyajohnny** [comment]
Je hebt je code een beetje raar geplakt, dus heb geen idee wat er precies in je configuration.yaml staat, maar dit zou volgens mij moeten werken:
```
sensor:
  - platform: afvalinfo
    id: Afval thuis
    resources:
      - type: gft
        friendly_name: GFT
      - type: kerstboom
        friendly_name: Kerstboom
      - type: pbd
        friendly_name: PBD
      - type: papier
        friendly_name: Papier
      - type: restafval
        friendly_name: Restafval
      - type: textiel
        friendly_name: Textiel
      - type: trash_type_today
        friendly_name: Afval vandaag
      - type: trash_type_tomorrow
        friendly_name: Afval morgen
    location: Stadskanaal
    postcode: 9591AX
    streetnumber: '4'
    streetnumbersuffix: ''
    district: ''
    diftarcode: ''
    dateformat: '%d-%m-%Y'
    locale: nl
    notrashtext: geen
    getwholeyear: false
```
