### ISSUE TITLE
Invalid options in Afvalinfo sensor

### ISSUE THREAD

**Issue by Misha57** [heyajohnny/afvalinfo#404]
Hi,

A few days ago i updated HA core to 23.11.3. Now i see config errors to afval.yaml file. This worked for the at least a year. 
I have now updated the config with the config tool on GitHub and get the same errors.
I also updated the core to 23.12.0 with the same errors.
I also updated afvalinfo to v2.0.3 with the same errors.
What is wrong with my config?

Configuration warnings
Invalid config for 'sensor.afvalinfo' at sensors/afval.yaml, line 21: 'id' is an invalid option for 'sensor.afvalinfo', check: id
Invalid config for 'sensor.afvalinfo' at sensors/afval.yaml, line 22: 'resources' is an invalid option for 'sensor.afvalinfo', check: resources
Invalid config for 'sensor.afvalinfo' at sensors/afval.yaml, line 45: 'location' is an invalid option for 'sensor.afvalinfo', check: location
Invalid config for 'sensor.afvalinfo' at sensors/afval.yaml, line 46: 'postcode' is an invalid option for 'sensor.afvalinfo', check: postcode
Invalid config for 'sensor.afvalinfo' at sensors/afval.yaml, line 47: 'streetnumber' is an invalid option for 'sensor.afvalinfo', check: streetnumber
Invalid config for 'sensor.afvalinfo' at sensors/afval.yaml, line 48: 'streetnumbersuffix' is an invalid option for 'sensor.afvalinfo', check: streetnumbersuffix
Invalid config for 'sensor.afvalinfo' at sensors/afval.yaml, line 49: 'district' is an invalid option for 'sensor.afvalinfo', check: district
Invalid config for 'sensor.afvalinfo' at sensors/afval.yaml, line 50: 'diftarcode' is an invalid option for 'sensor.afvalinfo', check: diftarcode
Invalid config for 'sensor.afvalinfo' at sensors/afval.yaml, line 51: 'dateformat' is an invalid option for 'sensor.afvalinfo', check: dateformat
Invalid config for 'sensor.afvalinfo' at sensors/afval.yaml, line 52: 'locale' is an invalid option for 'sensor.afvalinfo', check: locale
Invalid config for 'sensor.afvalinfo' at sensors/afval.yaml, line 53: 'notrashtext' is an invalid option for 'sensor.afvalinfo', check: notrashtext
Invalid config for 'sensor.afvalinfo' at sensors/afval.yaml, line 54: 'getwholeyear' is an invalid option for 'sensor.afvalinfo', check: getwholeyear

Home Assistant
Core 2023.12.0
Supervisor 2023.11.6
Operating System 11.2
Frontend 20231206.0

```
# - platform: afvalinfo
#   id: Afval_Ophalen
#   resources:
#     - gft
#     - kerstboom
#     - pbd
#     - papier
#     - restafval
#     - textiel
#     - trash_type_today
#     - trash_type_tomorrow
#   location: Nieuwegein
#   postcode: 1234XX
#   streetnumber: xx
#   dateformat: "%d-%m-%Y"
#   locale: "nl"
#   timespanindays: 365

- platform: afvalinfo
  id: Afval_Ophalen
  resources:
    - type: gft
      friendly_name: GFT
    - type: grofvuil
      friendly_name: Grofvuil
    - type: kca
      friendly_name: KCA
    - type: kerstboom
      friendly_name: Kerstboom
    - type: pbd
      friendly_name: PBD
    - type: papier
      friendly_name: Papier
    - type: restafval
      friendly_name: Restafval
    - type: takken
      friendly_name: Takken
    - type: textiel
      friendly_name: Textiel
    - type: trash_type_today
      friendly_name: Afval vandaag
    - type: trash_type_tomorrow
      friendly_name: Afval morgen
  location: Nieuwegein
  postcode: 1234XX
  streetnumber: 'xx'
  streetnumbersuffix: ''
  district: ''
  diftarcode: ''
  dateformat: '%d-%m-%Y'
  locale: nl
  notrashtext: geen
  getwholeyear: false
``` 

Regards Misha.
