### ISSUE TITLE
paar vraagjes

### ISSUE THREAD

**Issue by 1mfaasj** [heyajohnny/afvalinfo#445]
Hi. ik heb een paar vraagjes.

1. Is het mogelijk dat je een paar icons opneemt in je integratie? Kun je de afval momenten mooi weergeven zoals hier:
![image](https://github.com/user-attachments/assets/7f236e73-a074-4bfc-a72b-35132ba14619)
Je zou dan tijdens het maken van de sensoren een "entity_picture' kunnen meegeven:
```
homeassistant:
  customize:
    sensor.afvalinfo_home_gft:
      friendly_name: GFT
      entity_picture: /local/afvalinfo/GFT.png
    sensor.afvalinfo_home_papier:
      friendly_name: Papier
      entity_picture: /local/afvalinfo/Papier.png
    sensor.afvalinfo_home_pbd:
      friendly_name: PMD
      entity_picture: /local/afvalinfo/PMD.png
    sensor.afvalinfo_home_restafval:
      friendly_name: Restafval
      entity_picture: /local/afvalinfo/Restafval.png
```

Je vind de icons hier (gepikt vanuit een andere afval integratie): https://github.com/xirixiz/my-hass-config/tree/master/www/afvalwijzer

2. Je zou de friendly name ook kunnen meenemen, scheelt weer een paar stappen uit je readme en gemak voor je gebruikers.

3. is er een reden waarom je geen https gebruikt in de trashapi url? aangezien deze wel lijkt te werken, maar ook vanwege versleuteling van data: http://trashapi.azurewebsites.net

4. Uit interesse. Mag ik vragen waar trashapi de data vandaan haalt? Uit mijn gemeente (6129) is RWM de afvalverwerker, echter heeft deze issues vandoor andere afval integraties niet werken op dit moment, dus het komt ergens anders vandaan ga ik vanuit.

5. Hoever vooruit wordt data opgehaald? aangezien de kerstboom sensor nog op onbekend staat. en een refresh wordt elke 10 minuten gedaan denk ik (obv HA scaninterval?)

Alvast bedankt
