### ISSUE TITLE
Plase add: Hilversum

### ISSUE THREAD

**Issue by oleksanderkorn** [heyajohnny/afvalinfo#47]
Calendar: https://inzamelkalender.gad.nl/

**Comment by heyajohnny** [comment]
note to myself: Alkmaar + hvc also have https://inzamelkalender.___.nl

**Comment by heyajohnny** [comment]
I've just added Hilversum. Please let me know if all works fine.

**Comment by oleksanderkorn** [comment]
Thanks for an update.
I tried to enable it and i see that all entities have unknown state.
Configuration:
```
- platform: afvalinfo
    resources:
      - restafval
      - papier
      - textiel
      - pbd
      - gft
      - trash_type_today
    city: hilversum
    postcode: 1211NK
    streetnumber: 65
```
Entities:
![image](https://user-images.githubusercontent.com/9252017/79116758-9579cb00-7d89-11ea-95c7-0e2ab6f88dfc.png)
UI-Lovelace:
![image](https://user-images.githubusercontent.com/9252017/79116780-a296ba00-7d89-11ea-9b62-71a2e6eb0cb5.png)
```
  - title: Afval
    icon: mdi:recycle
    id: avfalinfo
    cards:
      - type: horizontal-stack
        cards:
          - type: entity
            entity: sensor.afvalinfo_gft
          - type: entity
            entity: sensor.afvalinfo_oud_papier
      - type: horizontal-stack
        cards:
          - type: entity
            entity: sensor.afvalinfo_pbd
          - type: entity
            entity: sensor.afvalinfo_restafval
      - type: horizontal-stack
        cards:
          - type: entity
            entity: sensor.afvalinfo_textiel
          - type: entity
            entity: sensor.afvalinfo_today
```

Maybe the problem is in the missing apartment number, because in gad you should also choose a specific apartment number if it is not a house but and apartment, e.g.  https://inzamelkalender.gad.nl/adres/1211NK:65:20
