### ISSUE TITLE
Sensors don't give info

### ISSUE THREAD

**Issue by Roelofk85** [heyajohnny/afvalinfo#51]
Hello,

Installed via HACS, when i idd the sensor to my configuration the sensors don't give info.
The status it gives is "Unknown", what am i doing wrong?

Thanks...

**Comment by heyajohnny** [comment]
What are the sensor parameters you use?
Should look something like this:
![image](https://user-images.githubusercontent.com/20553716/78507227-285da880-777f-11ea-9501-1448610a10b4.png)

**Comment by Roelofk85** [comment]
```
  - platform: afvalinfo
    city: "midsland"
    resources:
      - gft
      - papier
      - restafval
      - trash_type_today
      - trash_type_tomorrow
    postcode: 8891GV
    streetnumber: 1
    timespanindays: 365
```
