### ISSUE TITLE
Something went wrong while splitting data ... 'restafval' is not supported on your location

### ISSUE THREAD

**Issue by GitHubxtsnl** [heyajohnny/afvalinfo#84]
running HA 0.109.6
on a Pi4
running avfalinfo 50b32a4
------------------
Log Details (WARNING)
Logger: custom_components.afvalinfo.const.const
Source: custom_components/afvalinfo/location/suez.py:51
Integration: afvalinfo (documentation)
First occurred: 8:36:46 PM (1 occurrences)
Last logged: 8:36:46 PM

Something went wrong while splitting data: AttributeError("'NoneType' object has no attribute 'i'"). This probably means that trash type 'restafval' is not supported on your location

**AND**

Log Details (WARNING)
Logger: custom_components.afvalinfo.const.const
Source: custom_components/afvalinfo/location/suez.py:53
Integration: afvalinfo (documentation)
First occurred: 8:36:46 PM (1 occurrences)
Last logged: 8:36:46 PM

Something went wrong while splitting data: AttributeError("'NoneType' object has no attribute 'i'"). This probably means that trash type 'restafval' is not supported on your location

The message above always comes up 2 times after a restart of HA. I do not have **restafval** configured as an option in the sensor configuration, see below.

my config looks like this:

```
sensor:
  - platform: afvalinfo
    resources:
      - pbd
      - gft
      - papier
      - textiel
      - trash_type_today
    city: !secret general_address_city
    postcode: !secret general_address_zipcode
    streetnumber: !secret general_address_number
    dateformat: '%A %d %B'
    timespanindays: 365
```
