### ISSUE TITLE
No data when DSMR is enabled

### ISSUE THREAD

**Issue by EvertJob** [heyajohnny/afvalinfo#94]
Hi,

I'm having a strange issue.

This is my configuration.yaml file:
```
sensor:                       
    - platform: afvalinfo     
      resources:              
        - gft            
        - papier         
        - pbd        
        - trash_type_today
        - trash_type_tomorrow
      city: almere           
      postcode: f       
      streetnumber: f       
      dateformat: '%d-%m-%Y'
      locale: 'nl'           
      timespanindays: 365    
                             
sensor:                  
    - platform: dsmr_reader 
                            
binary_sensor:              
  - platform: meteoalarm   
    country: 'NL'        
    province: 'Flevoland'
```

With this configuration I can see DSMR data and the data from metroalarm but no data from the afvalinfo plugin. When I remove the DSMR Reader the data from afvalinfo is working as expected.

It doesn't matter which combination is used, as long DSMR and Afvalinfo are in the same configuration one of the two stops working.

I cannot figure out what the issue is, the logs are not giving any data about it so I'm going dark in here.

Are the more people with the same issue, or people who got it working and are willing to share that part of there config?
