### ISSUE TITLE
Error in the configuration.yaml

### ISSUE THREAD

**Issue by Palerm0** [heyajohnny/afvalinfo#95]
I`f installed afvalinfo via hacs.
Then I`m updating the configuration.yaml with the folowing:
``` 
sensor:
  - platform: afvalinfo
    resources:                       (at least 1 required)
      - pbd
      - trash_type_today
    city: westerkwartier            (required, default = sliedrecht)
    postcode: 1111xx                (required, default = 3361AB)
    streetnumber: xx                (required, default = 1)
    timespanindays: 365              (optional, default = 365) number of days to look into the future
```
The homeassistant Configuration validation button gives me an error:
```
Invalid config for [sensor.afvalinfo]: value is not allowed @ data['resources'][0]. Got '('. (See ?, line ?).
```
I`f tested all the parts in the config. it seems that there is an error in this part. But I cannot find where:
```
  resources:                       (at least 1 required)
      - pbd
      - trash_type_today
```
When I commend this out the rest of the config is good. If I test the complete config in yamllint. it all checks out.

Something wrong with the config?

Greetings
Palermo

**Comment by heyajohnny** [comment]
I think it's because of the parentheses. Remove the parentheses and the information in it and it should work. So your example above should look like this:
```
sensor:
  - platform: afvalinfo
    resources:
      - pbd
      - trash_type_today
    city: westerkwartier
    postcode: 1111xx
    streetnumber: xx
    timespanindays: 365
```
